import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime"

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  if(!user) return null;

  return (
  <div className="flex w-full gap-3">
    <Image className="flex h-14 w-14 rounded-full" src={user.profileImageUrl} alt="profile image" width={56} height={56}/>
    <input placeholder="passe o papo" className="grow bg-transparent outline-none"/>
  </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const {post, author} = props;
  return (
    <div key={post.id} className="flex p-4 border-b border-slate-300 gap-3">
      <Image className="h-14 w-14 rounded-full" src={author.profileImageUrl} alt={`@${author.username} profile picture`} width={56} height={56}/>
      <div className="flex flex-col">
        <div className="flex text-slate-400 gap-2"><span>{`@${author.username}`}</span><span>{`·  ${dayjs(post.createdAt).fromNow()}`}</span></div>
        <span>{post.content}</span>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser();
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full md:max-w-2xl border-x border-slate-400">
          <div className="flex border-b border-slate-400 p-4 ">
            {!user.isSignedIn && <div className="flex justify-center"><SignInButton/></div>}
            {!!user.isLoaded && <CreatePostWizard/>}
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (<PostView {...fullPost} key={fullPost.post.id}/>))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
